name: Docker CI

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.nush.app
          repository: appventure-website-v4
          tags: latest
