name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to AppVenture registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.nush.app

      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.nush.app/appventure-website-v4:latest
          build-args: |
            STATIC_URL=https://large.nush.app

      - name: Check if static files changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            static:
              - 'static-large/**'

      - name: Push large static files image to AppVenture registry
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.static == 'true'
        with:
          context: ./static-large
          push: true
          tags: registry.nush.app/appventure-website-v4:static-latest